apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:      
      imagePullSecrets:
        - name: regcred
      containers:
      - name: auth
        image: gitlab.lnu.se:5050/2dv013/student/team-2025-07-4chics/lihag-system/auth
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: JWT_PRIVATE_PEM
          valueFrom:
            secretKeyRef:
              name: lihag-env-vars
              key: JWT_PRIVATE_PEM
        - name: JWT_PUBLIC_PEM
          valueFrom:
            secretKeyRef:
              name: lihag-env-vars
              key: JWT_PUBLIC_PEM
        - name: DB_CONNECTION_STRING_AUTH
          valueFrom:
            secretKeyRef:
              name: lihag-env-vars
              key: DB_CONNECTION_STRING_AUTH
        - name: PROPERTY_URL
          valueFrom:
            secretKeyRef:
              name: lihag-env-vars
              key: PROPERTY_URL
        - name: MAINTENANCE_URL
          valueFrom:
            secretKeyRef:
              name: lihag-env-vars
              key: MAINTENANCE_URL
        volumeMounts:
          - name: jwt-public-key
            mountPath: /app/keys
            readOnly: true
      volumes:
        - name: jwt-public-key
          secret:
            secretName: jwt-public-key
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000