apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maintenance
  template:
    metadata:
      labels:
        app: maintenance
    spec:
      containers:
        - name: maintenance
          # OBS! Byt ut nedan till er GitLab Container Registry-path, t.ex. registry.gitlab.com/<user>/<repo>/maintenance:latest
          image: registry.gitlab.com/<user>/<repo>/maintenance:latest  # <-- GitLab Container Registry
          ports:
            - containerPort: 8888 # OBS! Uppdatera denna port då appen kommer att lyssna på en annan port. Glöm inte att även ändra i service.yaml.
          envFrom:
            - configMapRef:
                name: maintenance-config