apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maintenance
  template:
    metadata:
      labels:
        app: maintenance
    spec:
      containers:
        - name: maintenance
          image: gitlab.lnu.se:5050/2dv013/student/team-2025-07-4chics/lihag-system/maintenance
          imagePullPolicy: Always
          ports:
            - containerPort: 8002 # OBS! Uppdatera denna port då appen kommer att lyssna på en annan port. Glöm inte att även ändra i service.yaml.
          envFrom:
            - configMapRef:
                name: maintenance-config