apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maintenance
  template:
    metadata:
      labels:
        app: maintenance
    spec:
      containers:
        - name: maintenance
          image: gitlab.lnu.se:5050/2dv013/student/team-2025-07-4chics/lihag-system/maintenance
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          env:
          - name: DB_CONNECTION_STRING_MAINTENANCE
            valueFrom:
              secretKeyRef:
                name: lihag-env-vars
                key: DB_CONNECTION_STRING_MAINTENANCE
          - name: PROPERTY_URL
            valueFrom:
              secretKeyRef:
                name: lihag-env-vars
                key: PROPERTY_URL
          - name: RABBITMQ_URL
            valueFrom:
              secretKeyRef:
                name: lihag-env-vars
                key: RABBITMQ_URL
          - name: NODE_ENV
            valueFrom:
              secretKeyRef:
                name: lihag-env-vars
                key: NODE_ENV