apiVersion: v1
kind: Service
metadata:
  name: maintenance
spec:
  selector:
    app: maintenance
  ports:
    - port: 8002         # Porten som exponeras i klustret
      targetPort: 8002   # Porten som containern lyssnar p√•
  type: ClusterIP