apiVersion: apps/v1
kind: Deployment
metadata:
  name: property
spec:
  replicas: 3
  selector:
    matchLabels:
      app: property
  template:
    metadata:
      labels:
        app: property
    spec:
      containers:
        - name: property
          # OBS! Byt ut nedan till er GitLab Container Registry-path, t.ex. registry.gitlab.com/<user>/<repo>/property:latest
          image: registry.gitlab.com/<user>/<repo>/property:latest  # <-- GitLab Container Registry
          ports:
            - containerPort: 8888 # OBS! Uppdatera denna port då appen kommer att lyssna på en annan port. Glöm inte att även ändra i service.yaml.
          envFrom:
            - configMapRef:
                name: property-config