apiVersion: apps/v1
kind: Deployment
metadata:
  name: property
spec:
  replicas: 3
  selector:
    matchLabels:
      app: property
  template:
    metadata:
      labels:
        app: property
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: property
          image: gitlab.lnu.se:5050/2dv013/student/team-2025-07-4chics/lihag-system/property
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          env:
            - name: DB_CONNECTION_STRING_PROPERTY
              value: "$DB_CONNECTION_STRING_PROPERTY"
            - name: PORT
              value: "8006"
            - name: PROPERTY_URL
              value: "$PROPERTY_URL"
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "125m"