apiVersion: apps/v1
kind: Deployment
metadata:
  name: property
spec:
  replicas: 3
  selector:
    matchLabels:
      app: property
  template:
    metadata:
      labels:
        app: property
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: property
          image: gitlab.lnu.se:5050/2dv013/student/team-2025-07-4chics/lihag-system/property:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: property-config
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "125m"