apiVersion: v1
kind: Service
metadata:
  name: property
spec:
  selector:
    app: property
  ports:
    - port: 8003         # Porten som exponeras i klustret
      targetPort: 8003   # Porten som containern lyssnar p√•
  type: ClusterIP