apiVersion: v1
kind: Service
metadata:
  name: property
  labels:
    app: property
spec:
  type: NodePort
  selector:
    app: property
  ports:
    - name: http
      protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 31003