apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lihag-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: lihag.194.47.171.149.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lihag-frontend
                port:
                  number: 8888

          # - path: /admin
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: admin-frontend
          #       port:
          #         number: 8004

# l√§gg till frontend i ingressen?