apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: admin-frontend
                port:
                  number: 8004
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lihag-frontend
                port:
                  number: 8888

# l√§gg till frontend i ingressen?