apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lihag-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
        path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 8001
          service:
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 8000
          - path: /property(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: property
                port:
                  number: 8003
          - path: /maintenance(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: maintenance
                port:
                  number: 8002
# l√§gg till frontend i ingressen?