apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lihag-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 8888
          - path: /property(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: property
                port:
                  number: 8888
          - path: /maintenance(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: maintenance
                port:
                  number: 8888
          - path: /notification(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: notification
                port:
                  number: 8888