apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lihag-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /admin(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: 8888 # Ändra till rätt portnummer
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 8888 # Ändra till rätt portnummer
          - path: /tenant(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: tenant
                port:
                  number: 8888 # Ändra till rätt portnummer
          - path: /notification(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: notification
                port:
                  number: 8888 # Ändra till rätt portnummer