apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
spec:
  ingressClassName: traefik
  rules:
    - host: lihag.admin.194.47.171.149.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-frontend
                port:
                  number: 8004
    - host: lihag.194.47.171.149.nip.io
      http:
        paths:
          - path: /property
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 3000
          - path: /maintenance
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lihag-frontend
                port:
                  number: 8888

# l√§gg till frontend i ingressen?