apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - lihag.admin.194.47.171.20.nip.io
        - lihag.194.47.171.20.nip.io
        - auth.lihag.194.47.171.20.nip.io
      secretName: lihag-tls
  rules:
    - host: lihag.admin.194.47.171.20.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-frontend
                port:
                  number: 8004
    - host: lihag.194.47.171.20.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lihag-frontend
                port:
                  number: 8888
    - host: auth.lihag.194.47.171.20.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 3000

---
# --- ACME challenge ingress f√∂r cert-manager ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acme-challenge-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /.well-known/acme-challenge/
            pathType: Prefix
            backend:
              service:
                name: cert-manager
                port:
                  number: 8080