apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - lihag.admin.172.27.60.122.nip.io
        - lihag.172.27.60.122.nip.io
        - auth.lihag.172.27.60.122.nip.io
      secretName: lihag-tls
  rules:
    - host: lihag.admin.172.27.60.122.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-frontend
                port:
                  number: 8004
    - host: lihag.172.27.60.122.nip.io
      http:
         paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lihag-frontend
                port:
                  number: 8888
    - host: auth.lihag.172.27.60.122.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 3000
# l√§gg till frontend i ingressen?